NotificationsDatabase = "Notifications"
SitesDatabase = "Site"
SiteListCollection = "sites"
EmailCollection = "Emails"
NotificationListCollection = "NotificationList"
TimezoneListCollection = "TimezoneList"
ConfigurationListCollection = "ConfigurationsList"
ParkLoyaltyDatabase = "ParkLoyalty"
CronInfoCollection = "Crons"

NOTIFICATION_SOURCE_EMAIL_ID = "account@email-provider.com"